CREATE DATABASE IF NOT EXISTS bgo;

CREATE TABLE IF NOT EXISTS `bgo`.`users` (
  `id` VARCHAR(63) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `age` TINYINT(8) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

